import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Sparkles, Plus } from "lucide-react"

interface ResumeImprovementSuggestionsProps {
  jobTitle: string
}

export function ResumeImprovementSuggestions({ jobTitle }: ResumeImprovementSuggestionsProps) {
  // In a real app, these would be generated by AI based on the job and user's resume
  const suggestions = {
    summary: `As a Frontend Developer with strong React and TypeScript experience, I've built responsive web applications with a focus on performance and user experience. My background in modern JavaScript frameworks and CSS has enabled me to deliver intuitive interfaces that meet business requirements while maintaining code quality.`,

    experience: [
      {
        id: "1",
        original: "Developed React applications",
        improved:
          "Architected and developed responsive React applications that improved user engagement by 35% and reduced load times by 40%",
      },
      {
        id: "2",
        original: "Worked with TypeScript",
        improved:
          "Implemented TypeScript across the codebase, reducing production bugs by 27% and improving developer productivity",
      },
      {
        id: "3",
        original: "Created UI components",
        improved:
          "Designed and built a reusable component library that accelerated development cycles by 20% and ensured consistent UI across products",
      },
    ],

    skills: [
      {
        id: "1",
        original: "React",
        improved: "React (Redux, Context API, Hooks, React Router)",
      },
      {
        id: "2",
        original: "JavaScript",
        improved: "JavaScript (ES6+, async/await, Promises, DOM manipulation)",
      },
      {
        id: "3",
        original: "CSS",
        improved: "CSS (Flexbox, Grid, Animations, Responsive Design, Sass/SCSS)",
      },
    ],
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-amber-500" /> AI-Generated Resume Improvements
        </CardTitle>
        <CardDescription>Tailored suggestions to improve your resume for this {jobTitle} position.</CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="summary" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="summary">Summary</TabsTrigger>
            <TabsTrigger value="experience">Experience</TabsTrigger>
            <TabsTrigger value="skills">Skills</TabsTrigger>
          </TabsList>

          <TabsContent value="summary" className="mt-4 space-y-4">
            <div className="rounded-lg border p-4">
              <h4 className="mb-2 font-medium">Suggested Professional Summary</h4>
              <p className="text-sm text-muted-foreground">{suggestions.summary}</p>
              <div className="mt-4">
                <Button size="sm" className="gap-2">
                  <Plus className="h-3 w-3" /> Use This Summary
                </Button>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="experience" className="mt-4 space-y-4">
            {suggestions.experience.map((item) => (
              <div key={item.id} className="rounded-lg border p-4">
                <div className="space-y-2">
                  <div>
                    <h4 className="text-sm font-medium text-muted-foreground">Original:</h4>
                    <p className="text-sm">{item.original}</p>
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-green-600">Improved:</h4>
                    <p className="text-sm">{item.improved}</p>
                  </div>
                </div>
                <div className="mt-4">
                  <Button size="sm" variant="outline" className="gap-2">
                    <Plus className="h-3 w-3" /> Use Improved Version
                  </Button>
                </div>
              </div>
            ))}
          </TabsContent>

          <TabsContent value="skills" className="mt-4 space-y-4">
            {suggestions.skills.map((item) => (
              <div key={item.id} className="rounded-lg border p-4">
                <div className="space-y-2">
                  <div>
                    <h4 className="text-sm font-medium text-muted-foreground">Original:</h4>
                    <p className="text-sm">{item.original}</p>
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-green-600">Improved:</h4>
                    <p className="text-sm">{item.improved}</p>
                  </div>
                </div>
                <div className="mt-4">
                  <Button size="sm" variant="outline" className="gap-2">
                    <Plus className="h-3 w-3" /> Use Improved Version
                  </Button>
                </div>
              </div>
            ))}
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  )
}
